### ISSUE TITLE
[UI] 디자인 시스템 수정 및 일부 컴포넌트 추가

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#26]
## 내용
디자인 시스템에 아래 컴포넌트를 추가 구현합니다.
- 삭제/회원 탈퇴에 사용되는 bottomSheet
- 포킷/링크 더보기시 표시되는 bottomSheet
기존 PokitBottomSheet에서 close animation이 동작하지 않는 문제를 수정합니다.

<img src = "https://github.com/user-attachments/assets/05fd1524-7d40-44da-a293-35c9f575f261" width="48%" height="48%">
<img src = "https://github.com/user-attachments/assets/d544ae79-2c4b-4901-a67e-459971df5ab7" width="48%" height="48%">

## Todo
- [x] 기존 PokitBottomSheet 수정
- [x] 삭제/회원 탈퇴에 사용되는 bottomSheet 구현
- [x] 포킷/링크 더보기시 표시되는 bottomSheet 구현
- [x] 로그인 오류시 사용되는 bottomSheet 구현
