### ISSUE TITLE
[FEATURE] 로그인 프로세스 API 연동

### ISSUE THREAD

**Issue by jiwon2724** [YAPP-Github/pokit-android#29]
## 내용
로그인 프로세스 API를 연동합니다.

## Todo
- [ ] 중복 닉네임 검사 API 연동
- [ ] 카테고리 FlowRow 구현
- [ ] 로그인 API 연동
