### ISSUE TITLE
[UI] 8/22일자 UI 수정사항 반영

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#41]
## 내용
8월 22일에 올라온 수정사항_AOS을 반영합니다.

## Todo
- [x] 전체
  - [x] brand color code 수정
  - [x] 상단 system bar 색상 흰색으로 수정
- [x] 메인 화면
  - [x] 하단 네비게이션 버튼 클릭 영역 조절
  - [x] 포킷/미분류 버튼 크기 조정
  - [x] 미분류 텍스트 컬러 수정
  - [x] 타이틀 Text Weight 수정
  - [x] 포킷 내 아이콘 사이즈 수정
- [x] 포킷 수정 화면
  - [x] 포킷 목록에서 포킷 이름 색상 수정
  - [x] 포킷 이름 입력 창에 입력된 텍스트 색상 수정
  - [x] 화면 배경색상 수정
  - [x] 상단 toolbar 간격 조정
  - [x] 포킷 이미지 내 배경색상 제거
  - [x] toolbar와 포킷 이미지간 간격 조절
  - [x] 기본 포킷 이미지 설정 (푸키)
  - [x] 선택된 포킷 표시 라인 조절
- [x] 링크 추가 화면
  - [x] 화면 배경 색상 수정
  - [x] 저장 버튼을 하단에 고정
- [x] 검색 화면
  - [x] 배경 색상 수정
  - [x] 필터 chip 순서 수정
  - [ ] ~최근 검색어 여백 수정~
