### ISSUE TITLE
[FIX] 메인화면 QA 내용 수정

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#58]
## 내용
Android 테스트 케이스에서 발생한 문제사항을 수정합니다.
## Todo
공통  
- [x] 링크 기본 썸네일 이미지가 표시되지 않는 문제
- [ ] 읽은 링크도 안읽음으로 표시되는 문제  

링크 상세 bottomSheet  
- [x] 공유하기 클릭시 토스트 메세지 표시 추가  -> 현 단계에서는 공유하기 버튼 숨김으로 처리

메인-포킷  
- [x] 정렬 기준 변경시 반영되지 않는 문제
- [x] 미분류 링크 정렬 변경시 반영되지 않는 문제
- [x] 포킷 수정 클릭시 포킷 상세 페이지로 이동하는 문제
