### ISSUE TITLE
[FIX] 링크 상세 QA 사항 수정

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#64]
## 내용
링크 상세 화면에서 발생한 QA 사항을 수정합니다.
## Todo
- [x] 알림 아이콘이 항상 활성화되어 보이는 문제
- [x] 링크 상세 bottomSheet에서 포킷명이 항상 텍스트로 보이는 문제 수정
- [x] 즐겨찾기 버튼이 작동하지 않는 문제
- [x] (공통) 수정/추가/공유 bottomSheet에서 공유 항목 제거
