### ISSUE TITLE
[FIX] 1차 버젼 배포 전 QA

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#69]
## 내용
1차 버젼을 배포하기 전 수정해야 하는 QA 사항을 반영합니다.
## Todo
- [x] 포킷 수정시 자기 자신의 닉네임도 중복 검사하는 문제
- [x] 미분류 링크 목록에서 링크 상세 조회시 읽음 처리가 안되는 문제
- [x] 포킷 상세 첫 진입시 포킷 내 링크 개수가 0으로 표시되던 문제
- [x] 링크 상세 bottomSheet에 수정/삭제 클릭 이벤트 누락 수정
- [x] Figma 디자인 QA 사항 
  - [x] 헤더 높이 통일
  - [x] bottomSheet 그림자 수정
- [x] 링크 수정시 간혹 링크 이미지가 안보이는 문제
- [x] 알람 화면에서 알람 비엉있을 때 UI 추가
