### ISSUE TITLE
[UI] 일부 UI 수정

### ISSUE THREAD

**Issue by l5x5l** [YAPP-Github/pokit-android#79]
## 내용
10월 23일자로 안건에 올라온 내용의 확정 부분 중 현재 수정가능한 UI를 수정합니다.
단, 아직 구현되지 않은 공유 포킷, 포킷 정렬 고정과 관련된 내용은 제외합니다.
## Todo
- [x] 엠티 화면일 때 포킷 추가하기, 링크 추가하기 버튼 추가
- [x] 검색 화면의 placeHolder 문구 수정
- [x] 포킷 상세 화면에서 링크 추가 float button 추가
- [x] 메인 화면에서 링크 추가와 관련된 Toast UI 추가 (저장완료, 실패, 저장공간 부족)
- [x] 링크 추가 화면에서 링크 입력시 링크카드 로딩 ui 추가
- [x] 안읽음/즐겨찾기 화면 구현

## 다음 스프린트로 이동한 항목
- [ ] 링크 상세 bottomSheet 수정

**Comment by l5x5l** [comment]
항목 추가 (11/3)
- 누락된 즐겨찾기/안읽음 페이지 UI 구현 부분 추가

**Comment by l5x5l** [comment]
항목 수정 (11/12)  
- 작업 분리로 메인 화면 포킷에서 정렬 UI 변경부분 제거

**Comment by l5x5l** [comment]
항목 수정 (11/17)
- 링크 상세 bottomSheet의 경우 추가적인 서버 API 수정이 필요할 것으로 보여 다음 스프린트로 이동
  - 기존 방식은 링크 상세 BottomSheet가 올라올 때 링크 상세조회 API를 호출한 경우 안읽음 처리가 읽음으로 변경됨되지만 수정 이후 방식의 경우에는 링크 상세 bottomSheet가 보여지더라도 안읽음 표시가 사라지면 안된다고 판단
  - 대신 읽은 상태로 변환할 수 있는 API가 추가되서 uriHandler로 uri을 웹뷰로 오픈할 떄 해당 API를 호출하는 방향으로 수정해야 할 것으로 예상
